baseURL = 'https://palharesdev-blog.vercel.app/'
languageCode = 'en-us'
title = 'PalharesDev Blog'

[params]
  description = "Blog pessoal"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"